# Generated by Django 4.2 on 2024-09-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_name',
            field=models.CharField(default='default_legal_name', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
