# Generated by Django 4.2 on 2024-10-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
