# Generated by Django 4.2 on 2024-10-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_office_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilities_type', models.SmallIntegerField(choices=[(0, 'Heating'), (1, 'Water Supply'), (2, 'Gas Supply'), (3, 'Electricity Supply'), (4, 'Waste Collection')])),
                ('date', models.DateField()),
                ('counter', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.office')),
            ],
        ),
    ]
