# Generated by Django 4.2 on 2024-10-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_utilities'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='utilities',
            constraint=models.UniqueConstraint(condition=models.Q(('date__month', models.F('date__month')), ('date__year', models.F('date__year'))), fields=('office', 'utilities_type'), name='unique_utility_per_month'),
        ),
    ]
