# Generated by Django 4.2 on 2024-10-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_utilities_unique_utility_per_month'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='utilities',
            name='unique_utility_per_month',
        ),
    ]
