# Generated by Django 4.2 on 2024-10-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_utilities_unique_utility_per_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('bank_account_number_IBAN', models.CharField(max_length=29, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('deal_value', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='records/pdfs/')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.office')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.provider')),
            ],
        ),
    ]
