# Generated by Django 4.2 on 2024-10-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_provider_record'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number__isnull', False)), fields=('company', 'phone_number'), name='unique_phone_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('company', 'email'), name='unique_email_per_company'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(fields=('company', 'bank_account_number_IBAN'), name='unique_iban_per_company'),
        ),
    ]
