# Generated by Django 4.2 on 2024-10-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_provider_unique_phone_number_per_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='bank_account_number_IBAN',
            field=models.CharField(max_length=29),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
