# Generated by Django 4.2 on 2024-10-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_provider_unique_iban_per_company_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Order',
        ),
    ]
