# Generated by Django 4.2 on 2024-12-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deal_value',
            field=models.IntegerField(blank=True, default=1000),
            preserve_default=False,
        ),
    ]
