# Generated by Django 4.2 on 2024-12-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_order_deal_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='utilities',
            name='utilities_type',
            field=models.SmallIntegerField(choices=[(0, 'Опалення'), (1, 'Водопостачання'), (2, 'Газопостачання'), (3, 'Електропостачання'), (4, 'Збір відходів')]),
        ),
    ]
