# Generated by Django 4.2 on 2024-12-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_utilities_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilities',
            name='counter',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
