# Generated by Django 4.2 on 2025-01-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_utilities_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deal_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
